# Para prevenir posibles errores

try:
    n1 = int(input("Ingre su primer numero: "))

# Vamos a ingresar a esta parte del coidgo siempre que ocurra un error arriba
except:
    print("Ocurrio un error")
